### ISSUE TITLE
Profile Notebook controller to understand why it is quite slow

### ISSUE THREAD

**Issue by clement-moulin-frier** [flowersteam/vivarium#26]
### Description
When running behaviors directly from a notebook (as explained in [this notebook](https://github.com/clement-moulin-frier/vivarium/blob/main/notebooks/quickstart_tutorial.ipynb)), the simulation is quite slow. I have made a quick profiling, here is what I've observed (on my macbook):

- A full simulation step from the notebook takes aprrox. 0.1 second, which seems to be reasonable
- Most of this time is spent in `SimulatorController.pull_configs()`, which seems to be the bottleneck here

I think this speed is reasonable for educational purpose. However, when running behaviors from the notebooks, it seems that behaviors are not really what we would expect. For instance the agression behavior is quite often missing its target. We should better understand why it is the case.

### Steps to Reproduce
See above

### Environment (Optional)
- OS: MacOS on Macbook Pro

### Screenshots (Optional)
N/A

**Comment by corentinlger** [comment]
Notebook controller API changed.
